"""initial_schema

Revision ID: 0b0b47d517e0
Revises: 
Create Date: 2026-03-04 14:26:55.524333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0b47d517e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('revenue', sa.String(length=50), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('hq_location', sa.String(length=255), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('business_model', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack_json', sa.Text(), nullable=True),
    sa.Column('platform_adoption_json', sa.Text(), nullable=True),
    sa.Column('priorities_json', sa.Text(), nullable=True),
    sa.Column('competitive_json', sa.Text(), nullable=True),
    sa.Column('sales_motion', sa.String(length=20), nullable=True),
    sa.Column('snapshot_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('isv_solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industries_json', sa.Text(), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=True),
    sa.Column('business_outcomes_json', sa.Text(), nullable=True),
    sa.Column('pricing_model', sa.String(length=50), nullable=True),
    sa.Column('platform_vendor', sa.String(length=50), nullable=True),
    sa.Column('co_sell_status', sa.String(length=50), nullable=True),
    sa.Column('integration_depth', sa.String(length=50), nullable=True),
    sa.Column('cert_level', sa.String(length=50), nullable=True),
    sa.Column('affinity_score', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('companies_mentioned_json', sa.Text(), nullable=True),
    sa.Column('platform_relevance', sa.Float(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_url_hash'), 'news_items', ['url_hash'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('functional_area', sa.String(length=100), nullable=True),
    sa.Column('role_type', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tenure_years', sa.Float(), nullable=True),
    sa.Column('recent_activity', sa.Text(), nullable=True),
    sa.Column('platform_relevance_score', sa.Float(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_table('seller_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('news_item_id', sa.Integer(), nullable=True),
    sa.Column('platform_vendor', sa.String(length=50), nullable=False),
    sa.Column('sales_motion', sa.String(length=20), nullable=True),
    sa.Column('conversation_brief_json', sa.Text(), nullable=True),
    sa.Column('isv_recommendations_json', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('priority_reasoning', sa.Text(), nullable=True),
    sa.Column('coaching_status', sa.String(length=50), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_tasks_seller_id'), 'seller_tasks', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_tasks_status'), 'seller_tasks', ['status'], unique=False)
    op.create_table('coaching_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('messages_json', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('action_items_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['seller_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_sessions_seller_id'), 'coaching_sessions', ['seller_id'], unique=False)
    op.create_table('roleplay_scorecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=False),
    sa.Column('product_knowledge', sa.Integer(), nullable=True),
    sa.Column('contact_knowledge', sa.Integer(), nullable=True),
    sa.Column('objection_handling', sa.Integer(), nullable=True),
    sa.Column('conversation_flow', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('areas_to_practice_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coaching_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roleplay_scorecards_seller_id'), 'roleplay_scorecards', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roleplay_scorecards_seller_id'), table_name='roleplay_scorecards')
    op.drop_table('roleplay_scorecards')
    op.drop_index(op.f('ix_coaching_sessions_seller_id'), table_name='coaching_sessions')
    op.drop_table('coaching_sessions')
    op.drop_index(op.f('ix_seller_tasks_status'), table_name='seller_tasks')
    op.drop_index(op.f('ix_seller_tasks_seller_id'), table_name='seller_tasks')
    op.drop_table('seller_tasks')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_news_items_url_hash'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_table('isv_solutions')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
